<input type="hidden" name="<?php echo $this->getName() ?>" id="render_container_position_input" class="required-entry"
       value="<?php echo $this->getValue() ?>"/>
<div class="product-badges-chooser-line">
    <div data-position="top-left"
         class="product-badges-chooser-position-box product-badges-chooser-position-box-allowed"></div>
    <div class="product-badges-chooser-position-box product-badges-chooser-position-box-disabled"></div>
    <div data-position="top-right"
         class="product-badges-chooser-position-box product-badges-chooser-position-box-allowed"></div>
</div>
<div class="product-badges-chooser-line">
    <div class="product-badges-chooser-position-box product-badges-chooser-position-box-disabled"></div>
    <div class="product-badges-chooser-position-box product-badges-chooser-position-box-disabled"></div>
    <div class="product-badges-chooser-position-box product-badges-chooser-position-box-disabled"></div>
</div>
<div class="product-badges-chooser-line">
    <div data-position="bottom-left"
         class="product-badges-chooser-position-box product-badges-chooser-position-box-allowed"></div>
    <div class="product-badges-chooser-position-box product-badges-chooser-position-box-disabled"></div>
    <div data-position="bottom-right"
         class="product-badges-chooser-position-box product-badges-chooser-position-box-allowed"></div>
</div>
